/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InstanceCallBackMethod */

#ifndef _Included_InstanceCallBackMethod
#define _Included_InstanceCallBackMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InstanceCallBackMethod
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InstanceCallBackMethod_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
