/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Primitive */

#ifndef _Included_Primitive
#define _Included_Primitive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Primitive
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Primitive_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Primitive
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Primitive_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Primitive
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Primitive_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Primitive
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Primitive_div
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
