/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pustian_HelloJNI */

#ifndef _Included_pustian_HelloJNI
#define _Included_pustian_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pustian_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pustian_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
