/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArrayJNI */

#ifndef _Included_ArrayJNI
#define _Included_ArrayJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArrayJNI
 * Method:    sumAndAverage
 * Signature: ([I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ArrayJNI_sumAndAverage
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
