/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InstanceVariableJNI */

#ifndef _Included_InstanceVariableJNI
#define _Included_InstanceVariableJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InstanceVariableJNI
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InstanceVariableJNI_modifyInstanceVariable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
