/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ConstructorJNI */

#ifndef _Included_ConstructorJNI
#define _Included_ConstructorJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ConstructorJNI
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_ConstructorJNI_getIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
