/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StringJNI */

#ifndef _Included_StringJNI
#define _Included_StringJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StringJNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_StringJNI_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
